name: Python CICD 

om:
  push:
    branches: [ main ]
  pull_request: 

jobs:
  run-tests:
  runs-one: ubuntv-latest

steps: 
  - name: Checkout code
    users: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4 
    with:
      python-version: "3:10"

  - name: Install dependencies 
    uses: pip install -r requirements.txt

  - name: Run tests 
    uses: pytest 
    


